#!/bin/sh

# Temporal list of commands I will need
# local running=$(VBoxManage list runningvms | ${sedcmd} -r 's/^"(.*)".*$/\1/')
# VBoxManage controlvm $n reset
# VBoxManage list vms

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

show_help() {
	echo "here comes the help"
}


while :; do
  case $1 in
    -h|-\?|--help)
      show_help    # Display a usage synopsis.
      exit
      ;;

    -l|--list)
      VBoxManage list vms | sed -r 's/^"(.*)".*$/\1/'
      exit
      ;;

    -r|--running)
      VBoxManage list runningvms | sed -r 's/^"(.*)".*$/\1/'
      exit
      ;;

    -s|--start)
      if [ "$2" ]; then
        VBoxManage startvm "$2" --type headless
      else
        die 'ERROR: "--start" requires a non-empy option argument'
      fi
      exit
      ;;

    -k|--kill)
      if [ "$2" ]; then
        VBoxManage controlvm "$2" poweroff
      else
        die 'ERROR: "--kill" requires a non-empy option argument'
      fi
      exit
      ;;


    -?*)
      printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
      ;;

    *)               # Default case: No more options, so break out of the loop.
      break
  esac

  shift
done

